# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Dancer Demo"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "bootstrap"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# plugins
        # THE CONFIG-FILE SET 
        #     config:
        #         provider: Config
        #         users:
        #             - user: dave
        #               pass: pass
        #               roles:
        #                 - Admin
        #                 - Developer
        #             - user: user
        #               pass: pass
        #               roles:
        #                 - User
# Under normal circumstances, login/pass in a repo is a no-no, but this is demo only
plugins:
    DBIC:
        default:
            dsn: dbi:mysql:database=dancer_demo;host=localhost
            schema_class: MyApp::Schema
            user: dancer 
            password: password
    Auth::Extensible:
        login_page_handler: 'Demo::login_page_handler'
        permission_denied_page_handler: 'Demo::permission_denied_page_handler'
        realms:
            users:
                provider: 'DBIC'
                users_source: 'User'
                roles_source: 'Role'
                user_roles_source: 'UserRole'
                users_username_column:      username
                users_password_column:      password
                roles_role_column:          rolename
                users_lastlogin_column:     lastlogin 
                users_pwresetcode_column:   pw_reset_code 
                users_pwchanged_column:     pw_changed 
                roles_key: roles
                user_valid_conditions:
                    deleted: 0
                    # account_request: 
                    #     "<": 1

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '[%'
      end_tag:   '%]'

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1
